Bump the prod-deps group with 2 updates (#547)
Bumps the prod-deps group with 2 updates:
[org.jetbrains.kotlin:kotlin-bom](https://github.com/JetBrains/kotlin)
and org.jetbrains.kotlin:kotlin-maven-plugin.

Updates `org.jetbrains.kotlin:kotlin-bom` from 2.2.0 to 2.2.10
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/releases">org.jetbrains.kotlin:kotlin-bom's
releases</a>.</em></p>
<blockquote>
<h2>Kotlin 2.2.10</h2>
<h2>Changelog</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79276"><code>KT-79276</code></a>
Dexing fails with &quot;Cannot read field X because <!-- raw HTML
omitted --> is null&quot; with 2.2.0</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79442"><code>KT-79442</code></a>
&quot;Multiple annotations of type
kotlin.coroutines.jvm.internal.DebugMetadata&quot;: 2.2.0-Beta1
generates broken code with JVM default suspend methods in
interfaces</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78815"><code>KT-78815</code></a>
<code>Symbol not found: __ZNSt3__117bad_function_callD1Ev</code> error
on iOS 15.5 simulator in Xcode 16.3 after update to 2.2.0-Beta2</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78501"><code>KT-78501</code></a>
K2: Missing [ABSTRACT_SUPER_CALL] diagnostics for delegated interface
method leads to AssertionError: isCompiledToJvmDefault during IR
lowering</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78479"><code>KT-78479</code></a>
IR lowering failed / Unexpected null argument for composable call</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-76477"><code>KT-76477</code></a>
Kotlin/Native: fix compiler performance reporting in sources-&gt;klib
and klibs-&gt;binary</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78736"><code>KT-78736</code></a>
Missing [NOT_YET_SUPPORTED_IN_INLINE] diagnostics because of incorrect
context update</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-77685"><code>KT-77685</code></a>
&quot;IllegalArgumentException: Sequence contains more than one matching
element&quot;</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-76365"><code>KT-76365</code></a>
K2: Missing ABSTRACT_SUPER_CALL</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78352"><code>KT-78352</code></a>
False-positive IDENTITY_SENSITIVE_OPERATIONS_WITH_VALUE_TYPE when
comparing with equality operator (==)</li>
</ul>
<h3>Compose compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78479"><code>KT-78479</code></a>
Ensure that default transform affects functions entered through a
call</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78490"><code>KT-78490</code></a>
Fix visibility for default wrappers of protected methods</li>
<li><a
href="https://issuetracker.google.com/issues/408492167"><code>b/408492167</code></a>
Emit parameter names in Compose source information</li>
</ul>
<h3>JavaScript</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79050"><code>KT-79050</code></a>
KJS / IC: &quot;Unexpected body of primary constructor for processing
irClass&quot;</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79089"><code>KT-79089</code></a>
KJS: Could not load reporter / Cannot find module 'mocha' when running
jsNode tests</li>
</ul>
<h3>Native</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79075"><code>KT-79075</code></a>
Stuck on Kotlin_getSourceInfo_core_symbolication</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-76178"><code>KT-76178</code></a>
LLVM Update: symbol '__ZnwmSt19__type_descriptor_t' missing</li>
</ul>
<h3>Native. Runtime. Memory</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78925"><code>KT-78925</code></a>
Crash SIGABRT on Apple Watch after updating Kotlin to 2.2.0</li>
</ul>
<h3>Tools. CLI</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-77445"><code>KT-77445</code></a>
UNRESOLVED_REFERENCE when importing classes from kotlin-stdlib</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78263"><code>KT-78263</code></a>
java.lang.NoClassDefFoundError: Could not initialize class
com.intellij.psi.impl.PsiSubstitutorImpl</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78318"><code>KT-78318</code></a>
Unresolved reference when compiling kotlin/JS project on fresh
master</li>
</ul>
<h3>Tools. Compiler Plugins</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78490"><code>KT-78490</code></a>
&quot;AssertionError: SyntheticAccessorLowering should not attempt to
modify other files&quot; when calling protected open composable with
default argument</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78038"><code>KT-78038</code></a>
Make jvm-abi-gen compiler plugin output classloader-friendly</li>
</ul>
<h3>Tools. Gradle</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-77023"><code>KT-77023</code></a>
Support creating KotlinJvmAndroidCompilation in KotlinBaseApiPlugin</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md">org.jetbrains.kotlin:kotlin-bom's
changelog</a>.</em></p>
<blockquote>
<h2>2.2.10</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79276"><code>KT-79276</code></a>
Dexing fails with &quot;Cannot read field X because <!-- raw HTML
omitted --> is null&quot; with 2.2.0</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79442"><code>KT-79442</code></a>
&quot;Multiple annotations of type
kotlin.coroutines.jvm.internal.DebugMetadata&quot;: 2.2.0-Beta1
generates broken code with JVM default suspend methods in
interfaces</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78815"><code>KT-78815</code></a>
<code>Symbol not found: __ZNSt3__117bad_function_callD1Ev</code> error
on iOS 15.5 simulator in Xcode 16.3 after update to 2.2.0-Beta2</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78501"><code>KT-78501</code></a>
K2: Missing [ABSTRACT_SUPER_CALL] diagnostics for delegated interface
method leads to AssertionError: isCompiledToJvmDefault during IR
lowering</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78479"><code>KT-78479</code></a>
IR lowering failed / Unexpected null argument for composable call</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-76477"><code>KT-76477</code></a>
Kotlin/Native: fix compiler performance reporting in sources-&gt;klib
and klibs-&gt;binary</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78736"><code>KT-78736</code></a>
Missing [NOT_YET_SUPPORTED_IN_INLINE] diagnostics because of incorrect
context update</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-77685"><code>KT-77685</code></a>
&quot;IllegalArgumentException: Sequence contains more than one matching
element&quot;</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-76365"><code>KT-76365</code></a>
K2: Missing ABSTRACT_SUPER_CALL</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78352"><code>KT-78352</code></a>
False-positive IDENTITY_SENSITIVE_OPERATIONS_WITH_VALUE_TYPE when
comparing with equality operator (==)</li>
</ul>
<h3>Compose compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78479"><code>KT-78479</code></a>
Ensure that default transform affects functions entered through a
call</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78490"><code>KT-78490</code></a>
Fix visibility for default wrappers of protected methods</li>
<li><a
href="https://issuetracker.google.com/issues/408492167"><code>b/408492167</code></a>
Emit parameter names in Compose source information</li>
</ul>
<h3>JavaScript</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79050"><code>KT-79050</code></a>
KJS / IC: &quot;Unexpected body of primary constructor for processing
irClass&quot;</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79089"><code>KT-79089</code></a>
KJS: Could not load reporter / Cannot find module 'mocha' when running
jsNode tests</li>
</ul>
<h3>Native</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79075"><code>KT-79075</code></a>
Stuck on Kotlin_getSourceInfo_core_symbolication</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-76178"><code>KT-76178</code></a>
LLVM Update: symbol '__ZnwmSt19__type_descriptor_t' missing</li>
</ul>
<h3>Native. Runtime. Memory</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78925"><code>KT-78925</code></a>
Crash SIGABRT on Apple Watch after updating Kotlin to 2.2.0</li>
</ul>
<h3>Tools. CLI</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-77445"><code>KT-77445</code></a>
UNRESOLVED_REFERENCE when importing classes from kotlin-stdlib</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78263"><code>KT-78263</code></a>
java.lang.NoClassDefFoundError: Could not initialize class
com.intellij.psi.impl.PsiSubstitutorImpl</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78318"><code>KT-78318</code></a>
Unresolved reference when compiling kotlin/JS project on fresh
master</li>
</ul>
<h3>Tools. Compiler Plugins</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78490"><code>KT-78490</code></a>
&quot;AssertionError: SyntheticAccessorLowering should not attempt to
modify other files&quot; when calling protected open composable with
default argument</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78038"><code>KT-78038</code></a>
Make jvm-abi-gen compiler plugin output classloader-friendly</li>
</ul>
<h3>Tools. Gradle</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-77023"><code>KT-77023</code></a>
Support creating KotlinJvmAndroidCompilation in KotlinBaseApiPlugin</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/JetBrains/kotlin/commit/c448af19ded1b1a4e96e9af6412cd9acb100ce1a"><code>c448af1</code></a>
Add ChangeLog for 2.2.10-RC2</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/4925857c812473358266556396fa76ac15b0dffd"><code>4925857</code></a>
[JS] Upgrade NPM dependencies</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/0e3327f52acd563a7846ffdf65c6d87a1e4f7f30"><code>0e3327f</code></a>
[K/N] Use coreSymbolicationImageListType=all_loaded by default</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/21231f535f1777db97ea7ea39bcabb9f6ddcb9a5"><code>21231f5</code></a>
[JVM] avoid unnecessary spills of some dead locals</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/42972543940d3f519561162dec6f859d9ce73ac3"><code>4297254</code></a>
[gradle] Fix missing mocha reporter module</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/95639d5e5baf1dfdb71bdf5c7962865cc6053dc4"><code>95639d5</code></a>
[JVM] Fix detection of $DefaultImpl bridges</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/09a5926c90cc1dd1b9cd9b4bb0f2ba398635dcb8"><code>09a5926</code></a>
FIR: allow to resolve some Java classes with
<code>@kotlin.Metadata</code></li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/4bf855d50d78b8f346ac768eecceda0286f490c9"><code>4bf855d</code></a>
[K/JS] Fix incremental compilation for overridden external
properties</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/69050bd292fef7017f259d0839391a0fd2d6e66c"><code>69050bd</code></a>
[K/N][llvm] Update LLVM build to incorporate the recent changes</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/accbf36dfd0890efb10d2b927061903267447632"><code>accbf36</code></a>
Add ChangeLog for 2.2.10-RC</li>
<li>Additional commits viewable in <a
href="https://github.com/JetBrains/kotlin/compare/v2.2.0...v2.2.10">compare
view</a></li>
</ul>
</details>
<br />

Updates `org.jetbrains.kotlin:kotlin-maven-plugin` from 2.2.0 to 2.2.10

Updates `org.jetbrains.kotlin:kotlin-maven-plugin` from 2.2.0 to 2.2.10


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>